

#' @title Load metadata for a set of stations
#' @param Vector with stations (if not provided, the default returns all stations available)
#' @return A dataframe with metadata
#' @examples
#' regine_main <- c('1.48','1.49','1.50')
#' metadata <- get_metadata(regine_main)
#' @export

get_metadata <- function(regine_main = meta_data$regine_main) {

  isel <- sapply(regine_main, FUN = function(x) which(meta_data$regine_main == x))

  return(meta_data[isel, ])

}


#' @title Load data for a set of stations, average meteorological grids for the watershed
#' @description Runoff values stored on date yyyy-mm-dd are valid for the period from yyyy-mm-dd 00:00 to yyyy-mm-dd+1 00:00
#' @description Meteorological values stored on date yyyy-mm-dd are valid for the period from yyyy-mm-dd-1 06:00 to yyyy-mm-dd 06:00
#' @param path_met Path to folder with gridded meteorological data (requires netcdf files, and SeNorge version 2.0 and 2.1)
#' @param path_runoff Path to folder with files containing runoff data generated by lescon_var
#' @param regine_main Vector with stations (regine_area and main_no seperated by a full stop)
#' @param time_vec Vector with dates (using format from package lubridate)
#' @examples
#' library(lubridate)
#' path_met <- '//hdata/grid/metdata/met_obs_v2.0'
#' path_runoff <- '//hdata/fou/Vannbalansekart/Data/Runoff_All'
#' regine_main <- c('1.48','1.49','1.50')
#' time_vec <- seq(ymd("2011-01-01"), ymd("2011-01-04"), by = "days")
#' res <- load_data_mean(path_met, path_runoff, regine_main, time_vec)
#' @return A list with data for each station
#' @export

load_data_mean <- function(path_met, path_runoff, regine_main, time_vec) {

  # Test if metadata exist for stations

  if (!all(regine_main %in% meta_data$regine_main)) {

    imissing <- !(regine_main %in% meta_data$regine_main)

    station_str <- paste(regine_main[imissing], collapse = ", ")

    stop(paste("Lacking metadata for station", station_str, sep = " "))

  }

  # Initilize list for one station

  init_list <- function(regine_main_in) {

    # Link meta_data and wsh_index

    irow <- which(meta_data$regine_main == regine_main_in)

    drainage_basin_key <- as.character(meta_data$drainage_basin_key[irow])

    # Initilize list

    data_all <- list(time_vec = time_vec,
                     regine_main = regine_main_in,
                     wsh_index = wsh_index[[drainage_basin_key]],
                     metadata = dplyr::filter(meta_data, regine_main == regine_main_in),
                     Tair = NA, Prec = NA)

  }

  # Assign variable to general data structure

  assign_var <- function(istat, iday, variable) {

    data_all[[istat]][[variable]][iday] <- met_data[[istat]]
    data_all[[istat]]

  }

  # Initlize data structure

  data_all <- lapply(regine_main, init_list)

  # Loop over time

  for (iday in seq_along(time_vec)) {


    print(paste("Processing day ", iday, sep = ""))


    # Process air temperature data

    filename <- paste(path_met, "/tm/", format(time_vec[iday], "%Y"), "/tm_", format(time_vec[iday], "%Y_%m_%d"), ".nc", sep = "")

    met_data <- read_nc_file(filename)


#     filename <- paste(path_met, "/tm/", format(time_vec[iday], "%Y"), "/tm_", format(time_vec[iday], "%Y_%m_%d"), ".bil", sep = "")
#
#     met_data <- read_bil_file(filename)
#
#     met_data <- met_data/10 - 273.15



    # Extract data for stations

    met_data <- lapply(regine_main, load_single_wsh, grid_data = met_data)

    # Average data

    met_data <- lapply(met_data, mean)

    # Assign variable to data structure

    data_all <- lapply(seq_along(data_all), assign_var, iday = iday, variable = "Tair")


    # Process precipitation data

    filename <- paste(path_met, "/rr/", format(time_vec[iday], "%Y"), "/rr_", format(time_vec[iday], "%Y_%m_%d"), ".nc", sep = "")

    met_data <- read_nc_file(filename)


#     filename <- paste(path_met, "/rr/", format(time_vec[iday], "%Y"), "/rr_", format(time_vec[iday], "%Y_%m_%d"), ".bil", sep = "")
#
#     met_data <- read_bil_file(filename)
#
#     met_data <- met_data/10



    # Extract data for stations

    met_data <- lapply(regine_main, load_single_wsh, grid_data = met_data)

    # Average data

    met_data <- lapply(met_data, mean)

    # Assign variable to data structure

    data_all <- lapply(seq_along(data_all), assign_var, iday = iday, variable = "Prec")

  }

  # Get runoff data

  data_all <- lapply(data_all,load_runoff_all, path = path_runoff, time = time_vec)

  return(data_all)

}



#' @title Load data for a set of stations, aggregate meteorological grids for the watershed into 200m elevation bands
#' @description Runoff values stored on date yyyy-mm-dd are valid for the period from yyyy-mm-dd 00:00 to yyyy-mm-dd+1 00:00
#' @description Meteorological values stored on date yyyy-mm-dd are valid for the period from yyyy-mm-dd-1 06:00 to yyyy-mm-dd 06:00
#' @param path_met Path to folder with gridded meteorological data (requires netcdf files, and SeNorge version 2.0 and 2.1)
#' @param path_runoff Path to folder with files containing runoff data generated by lescon_var
#' @param regine_main Vector with stations (regine_area and main_no seperated by a full stop)
#' @param time_vec Vector with dates (using format from package lubridate)
#' @examples
#' library(lubridate)
#' path_met <- '//hdata/grid/metdata/met_obs_v2.0'
#' path_runoff <- '//hdata/fou/Vannbalansekart/Data/Runoff_All'
#' regine_main <- c('1.48','1.49','1.50')
#' time_vec <- seq(ymd("2011-01-01"), ymd("2011-01-04"), by = "days")
#' res <- load_data_elev(path_met, path_runoff, regine_main, time_vec)
#' @return A list with data for each station
#' @export

load_data_elev <- function(path_met, path_runoff, regine_main, time_vec) {

  # Test if metadata exist for stations

  if (!all(regine_main %in% meta_data$regine_main)) {

    imissing <- !(regine_main %in% meta_data$regine_main)

    station_str <- paste(regine_main[imissing], collapse = ", ")

    stop(paste("Lacking metadata for station", station_str, sep = " "))

  }

  # Initilize list for one station

  init_list <- function(regine_main_in) {

    # Link meta_data and wsh_index

    irow <- which(meta_data$regine_main == regine_main_in)

    drainage_basin_key <- as.character(meta_data$drainage_basin_key[irow])

    # Compute mean elevation and fraction of total area for each elevation band

    elev <- dem_vec[wsh_index[[drainage_basin_key]]]
    elev_zones <- cut(elev, breaks = seq(-200,4000,200), right = FALSE)
    elev_mean <- aggregate(elev, by = list(elev_zones), FUN = mean)
    elev_frac <- aggregate(rep(1, length(elev)), by = list(elev_zones), FUN = sum)
    elev_frac <- elev_frac$x / length(elev)

    # Initilize list

    data_all <- list(time_vec = time_vec,
                     regine_main = regine_main_in,
                     elev_mean = elev_mean$x,
                     frac_elev_band = elev_frac,
                     wsh_index = wsh_index[[drainage_basin_key]],
                     metadata = dplyr::filter(meta_data, regine_main == regine_main_in),
                     Tair = matrix(NA, nrow = length(time_vec) , ncol = length(elev_mean$x)),
                     Prec = matrix(NA, nrow = length(time_vec) , ncol = length(elev_mean$x)))
  }


  # Aggregate meteorological data over elevation zones

  aggregate_elevations <- function(met_data, data_all) {

    elev_wsh <- dem_vec[data_all$wsh_index]
    elev_as_factors <- cut(elev_wsh, breaks = seq(-200,4000,200), right = FALSE)
    res <- aggregate(met_data, by = list(elev_as_factors), FUN = mean)

    return(res$x)

  }

  # Assign variable to general data structure

  assign_var <- function(istat, iday, variable) {

    data_all[[istat]][[variable]][iday, ] <- met_data[[istat]]
    data_all[[istat]]

  }

  # Initlize data structure

  data_all <- lapply(regine_main, init_list)

  # Loop over time

  for (iday in seq_along(time_vec)) {


    print(paste("Processing day ", iday, sep = ""))


    # Process air temperature data

    filename <- paste(path_met, "/tm/", format(time_vec[iday], "%Y"), "/tm_", format(time_vec[iday], "%Y_%m_%d"), ".nc", sep = "")

    met_data <- read_nc_file(filename)

#     filename <- paste(path_met, "/tm/", format(time_vec[iday], "%Y"), "/tm_", format(time_vec[iday], "%Y_%m_%d"), ".bil", sep = "")
#
#     met_data <- read_bil_file(filename)
#
#     met_data <- met_data/10 - 273.15

    # Extract data for stations

    met_data <- lapply(regine_main, load_single_wsh, grid_data = met_data)

    # Aggregate data

    met_data <- mapply(aggregate_elevations, met_data, data_all, SIMPLIFY = FALSE)

    # Assign variable to data structure

    data_all <- lapply(seq_along(data_all), assign_var, iday = iday, variable = "Tair")


    # Process precipitation data

    filename <- paste(path_met, "/rr/", format(time_vec[iday], "%Y"), "/rr_", format(time_vec[iday], "%Y_%m_%d"), ".nc", sep = "")

    met_data <- read_nc_file(filename)

#     filename <- paste(path_met, "/rr/", format(time_vec[iday], "%Y"), "/rr_", format(time_vec[iday], "%Y_%m_%d"), ".bil", sep = "")
#
#     met_data <- read_bil_file(filename)
#
#     met_data <- met_data/10

    # Extract data for stations

    met_data <- lapply(regine_main, load_single_wsh, grid_data = met_data)

    # Aggregate data

    met_data <- mapply(aggregate_elevations, met_data, data_all, SIMPLIFY = FALSE)

    # Assign variable to data structure

    data_all <- lapply(seq_along(data_all), assign_var, iday = iday, variable = "Prec")

  }

  # Get runoff data

  data_all <- lapply(data_all,load_runoff_all, path = path_runoff, time = time_vec)

  return(data_all)

}


