

#' @title Write data for models using elevation zones
#' @param path_met Path to folder with gridded meteorological data (requires netcdf files, and SeNorge version 2.0 and 2.1)
#' @param path_runoff Path to folder with files containing runoff data generated by lescon_var
#' @param path_save Path to folder in which to save the output files
#' @param regine_main Vector with stations (regine_area and main_no seperated by a full stop)
#' @param time_vec Vector with dates (using format from package lubridate)
#' @return Data for runnig hydrological models
#' @examples
#' path_met <- '//hdata/grid/metdata/met_obs_v2.0'
#' path_runoff <- '//hdata/fou/Vannbalansekart/Data/Runoff_All'
#' path_save <- 'C:/Users/jmg/Desktop/testdata'   # Change to approprite folder
#' regine_main <- c('1.48','1.49','1.50')
#' time_vec <- seq(ymd("2011-01-01"), ymd("2011-01-04"), by = "days")
#' write_model_data(path_met, path_runoff, path_save, regine_main, time_vec)
#'
#' @export

write_model_data <- function(path_met, path_runoff, path_save, regine_main, time_vec) {

  # Function for save data from one watershed

  save_single_watershed <- function(data) {

    # Folder for saving the data

    folder_name <- paste(data$regine_main,"_data", sep = "")
    folder_name <- gsub("\\.", "_", folder_name)
    folder_name <- paste(path_save, "/", folder_name, sep = "")

    # Create directory

    dir.create(folder_name, showWarnings = FALSE)

    # Round data

    data$Tair <- round(data$Tair, digits = 2)
    data$Prec <- round(data$Prec, digits = 2)
    data$Runoff <- round(data$Runoff, digits = 2)
    data$frac_elev_band <- round(data$frac_elev_band, digits = 3)

    # From lists to data frames

    Tair  <- data.frame(Time = data$time_vec, Tair = data$Tair)
    Prec  <- data.frame(Time = data$time_vec, Prec = data$Prec)
    Q_obs <- data.frame(Time = data$time_vec, Qobs = data$Runoff)

    frac_elev_band <- data$frac_elev_band

    metadata <- data$metadata

    # Write data

    write.table(Tair, file = paste(folder_name, "/Tair.txt", sep = ""), sep = "\t", row.names = FALSE, col.names = FALSE)
    write.table(Prec, file = paste(folder_name, "/Prec.txt", sep = ""), sep = "\t", row.names = FALSE, col.names = FALSE)
    write.table(Q_obs, file = paste(folder_name, "/Qobs.txt", sep = ""), sep = "\t", row.names = FALSE, col.names = FALSE)
    write.table(frac_elev_band, file = paste(folder_name, "/frac_elev_band.txt", sep = ""), sep = "\t", row.names = FALSE, col.names = FALSE)
    write.table(metadata, file = paste(folder_name, "/metadata.txt", sep = ""), sep = ";", row.names = FALSE, quote = FALSE)

  }

  # Load data for all stations

  res <- load_data_elev(path_met, path_runoff, regine_main, time_vec)

  # Save data for all stations

  invisible(lapply(res, save_single_watershed))

}






