

#' @title Write data for models using elevation zones
#' @param path_met Path to folder with gridded meteorological data (requires netcdf files, and SeNorge version 2.0 and 2.1)
#' @param path_runoff Path to folder with files containing runoff data generated by lescon_var
#' @param path_model_data Path to folder in which to save the output files
#' @param regine_main Vector with stations (regine_area and main_no seperated by a full stop)
#' @param time_vec Vector with dates (using format from package lubridate)
#' @return Data for runnig hydrological models
#' @examples
#' path_met <- '//hdata/grid/metdata/met_obs_v2.0'
#' path_runoff <- '//hdata/fou/Avrenningskart/Data/Runoff_All'
#' path_model_data <- 'C:/Users/jmg/Desktop/testdata'   # Change to approprite folder
#' regine_main <- c('1.48','1.49','1.50')
#' time_vec <- seq(ymd(Sys.Date()-10), ymd(Sys.Date()-5), by = "days")
#' write_model_data(path_met, path_runoff, path_model_data, regine_main, time_vec)
#' @export

write_model_data <- function(path_met, path_runoff, path_model_data, regine_main, time_vec) {

  # Function for save data from one watershed

  save_single_watershed <- function(data) {

    # Folder for saving the data

    folder_name <- paste(data$regine_main,"_data", sep = "")
    folder_name <- gsub("\\.", "_", folder_name)
    folder_name <- paste(path_model_data, "/", folder_name, sep = "")

    # Create directory

    dir.create(folder_name, showWarnings = FALSE)

    # Round data

    data$Tair <- round(data$Tair, digits = 2)
    data$Prec <- round(data$Prec, digits = 2)
    data$Runoff <- round(data$Runoff, digits = 2)
    data$frac_elev_band <- round(data$frac_elev_band, digits = 3)

    # From lists to data frames

    Tair  <- data.frame(Time = data$time_vec, Tair = data$Tair)
    Prec  <- data.frame(Time = data$time_vec, Prec = data$Prec)
    Q_obs <- data.frame(Time = data$time_vec, Qobs = data$Runoff)

    frac_elev_band <- data$frac_elev_band

    metadata <- data$metadata

    # Write data

    write.table(Tair, file = paste(folder_name, "/Tair.txt", sep = ""), sep = "\t", row.names = FALSE, col.names = FALSE)
    write.table(Prec, file = paste(folder_name, "/Prec.txt", sep = ""), sep = "\t", row.names = FALSE, col.names = FALSE)
    write.table(Q_obs, file = paste(folder_name, "/Qobs.txt", sep = ""), sep = "\t", row.names = FALSE, col.names = FALSE)
    write.table(frac_elev_band, file = paste(folder_name, "/frac_elev_band.txt", sep = ""), sep = "\t", row.names = FALSE, col.names = FALSE)
    write.table(metadata, file = paste(folder_name, "/metadata.txt", sep = ""), sep = ";", row.names = FALSE, quote = FALSE)

  }

  # Load data for all stations

  res <- load_data_elev(path_met, path_runoff, regine_main, time_vec)

  # Save data for all stations

  invisible(lapply(res, save_single_watershed))

}


#' @title Update data for models
#' @param path_met Path to folder with gridded meteorological data (requires netcdf files, and SeNorge version 2.0 and 2.1)
#' @param path_runoff Path to folder with files containing runoff data generated by lescon_var
#' @param path_model_data Path to folder in which to save the output files
#' @param overlap Number of days in the old data to replace with new data
#' @return Data for runnig hydrological models
#' @examples
#' path_met <- '//hdata/grid/metdata/met_obs_v2.0'
#' path_runoff <- '//hdata/fou/Avrenningskart/Data/Runoff_All'
#' path_model_data <- 'C:/Users/jmg/Desktop/testdata'   # Change to approprite folder
#' regine_main <- c('1.48','1.49','1.50')
#' time_vec <- seq(ymd(Sys.Date()-10), ymd(Sys.Date()-5), by = "days")
#' overlap <- 2
#' write_model_data(path_met, path_runoff, path_model_data, regine_main, time_vec)
#' update_model_data(path_met, path_runoff, path_model_data, overlap)
#' @export

update_model_data <- function(path_met, path_runoff, path_model_data, overlap) {

  # Function for updating data for one watershed

  update_single_watershed <- function(data) {

    # Round data

    data$Tair <- round(data$Tair, digits = 2)
    data$Prec <- round(data$Prec, digits = 2)
    data$Runoff <- round(data$Runoff, digits = 2)

    # Read old data

    filename <- paste(path_model_data, "/", gsub("\\.", "_", data$regine_main), "_data/Tair.txt", sep = "")
    tmp <- read.table(filename, stringsAsFactors = FALSE)
    Tair_old <- data.frame(as.Date(tmp[,1]), tmp[ ,2:ncol(tmp)])
    colnames(Tair_old) <- c("Time", paste("Tair", 1:(ncol(tmp)-1), sep = "."))

    filename <- paste(path_model_data, "/", gsub("\\.", "_", data$regine_main), "_data/Prec.txt", sep = "")
    tmp <- read.table(filename, stringsAsFactors = FALSE)
    Prec_old  <- data.frame(Time = as.Date(tmp[,1]), Prec = tmp[ ,2:ncol(tmp)])
    colnames(Prec_old) <- c("Time", paste("Prec", 1:(ncol(tmp)-1), sep = "."))

    filename <- paste(path_model_data, "/", gsub("\\.", "_", data$regine_main), "_data/Qobs.txt", sep = "")
    tmp <- read.table(filename, stringsAsFactors = FALSE)
    Qobs_old  <- data.frame(Time = as.Date(tmp[,1]), Qobs = tmp[ ,2:ncol(tmp)])
    colnames(Qobs_old) <- c("Time", "Qobs")

    # From lists to data frames

    Tair_new <- data.frame(Time = data$time_vec, Tair = data$Tair)
    Prec_new <- data.frame(Time = data$time_vec, Prec = data$Prec)
    Qobs_new <- data.frame(Time = data$time_vec, Qobs = data$Runoff)

    # Merge data frames

    Tair_keep <- dplyr::anti_join(Tair_old, Tair_new, by = "Time")
    Tair_merged <- rbind(Tair_keep, Tair_new)
    Tair_merged <- Tair_merged[order(Tair_merged$Time), ]

    Prec_keep <- dplyr::anti_join(Prec_old, Prec_new, by = "Time")
    Prec_merged <- rbind(Prec_keep, Prec_new)
    Prec_merged <- Prec_merged[order(Prec_merged$Time), ]

    Qobs_keep <- dplyr::anti_join(Qobs_old, Qobs_new, by = "Time")
    Qobs_merged <- rbind(Qobs_keep, Qobs_new)
    Qobs_merged <- Qobs_merged[order(Qobs_merged$Time), ]

    # Write data

    filename <- paste(path_model_data, "/", gsub("\\.", "_", data$regine_main), "_data/Tair.txt", sep = "")
    write.table(Tair_merged, file = filename, sep = "\t", row.names = FALSE, col.names = FALSE)

    filename <- paste(path_model_data, "/", gsub("\\.", "_", data$regine_main), "_data/Prec.txt", sep = "")
    write.table(Prec_merged, file = filename, sep = "\t", row.names = FALSE, col.names = FALSE)

    filename <- paste(path_model_data, "/", gsub("\\.", "_", data$regine_main), "_data/Qobs.txt", sep = "")
    write.table(Qobs_merged, file = filename, sep = "\t", row.names = FALSE, col.names = FALSE)

  }

  # Get list of stations/watersheds in folder with model input data

  dirs <- list.dirs(path_model_data, recursive = FALSE)

  regine_main <- sapply(strsplit(dirs, "/"), tail, 1)
  regine_main <- gsub("_data", "", regine_main)
  regine_main <- gsub("_", ".", regine_main)

  # Get time of last avalibale model input data

  time_end_old <- read.table(file = paste(dirs[1], "/Tair.txt", sep = ""), sep = "\t", stringsAsFactors = FALSE)
  time_end_old <- as.Date(tail(time_end_old$V1,1))

  # Get time of last avalibale data in senorge

  time_end_meteo <- Sys.Date() + 20

  filetest <- paste(path_met, "/tm/", format(time_end_meteo, "%Y"), "/tm_", format(time_end_meteo, "%Y_%m_%d"), ".nc", sep = "")

  while (!file.exists(filetest)) {

    time_end_meteo <- time_end_meteo - 1
    filetest <- paste(path_met, "/tm/", format(time_end_meteo, "%Y"), "/tm_", format(time_end_meteo, "%Y_%m_%d"), ".nc", sep = "")

  }

  # Read new data

  time_vec <- seq(lubridate::ymd(time_end_old-overlap), lubridate::ymd(time_end_meteo), by = "days")

  res_new <- load_data_elev(path_met, path_runoff, regine_main, time_vec)

  # Update data for all stations

  invisible(lapply(res_new, update_single_watershed))

}




